dubbo:
  application:
    name: service-goods
  registry:
    address: zookeeper://192.168.195.188:2181
  protocol:
    port: -1
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql:///shop1909?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.195.188
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672
mybatis-plus:
  mapper-locations: classpath:com/qf/dao/*.xml
  configuration:
    #Mybatis会在控制台打印执行的sql语句 - 可以配合mybatis log插件使用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl