server:
  port: 8080
spring:
  thymeleaf:
    cache: false
dubbo:
  registry:
    address: zookeeper://192.168.195.188:2181
  consumer:
    check: false
  application:
    name: web-goods

fdfs:
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 192.168.195.188:22122
