dubbo:
  application:
    name: service-search
  registry:
    address: zookeeper://192.168.195.188:2181
  consumer:
    check: false
  protocol:
    port: -1
spring:
  data:
    solr:
      host: http://192.168.195.188:8983/solr/mycollection
